### Домашнее задание «Библиотека Pandas»

In [1]:
import pandas as pd

#### Задание 1
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [3]:
"""
Считал в ratings весь файл с оценками фильмов.
Оставил только стобцы movieId и rating
Затем в одно действие 
1) фильтранул с оценками 5;
2) сгруппировал по movieId и для каждой группы посчитал количество оценок
3) отсортировал по убыванию, чтобы фильм с наибольшим количеством оценок был первым
4) вывел только первую строку и записал все это в новый дата фрейм
Затем приджойнил к этому новому датафрейму данные из файла с названиями фильмов
Так вывелось название фильма с наибольшим количеством оценок 5

Пометка в папке ml-25m файлы заменил файлами из ml-latest-small.zip - git отказался такие больший файлы заливать
"""

ratings = pd.read_csv('ml-25m/ratings.csv')
movies_rating = ratings[['movieId','rating']]
result_film = movies_rating[movies_rating['rating'] == 5].groupby('movieId').count().sort_values(by='rating', ascending=False).head(1)

movies = pd.read_csv('ml-25m/movies.csv')
result_film.merge(movies, on='movieId', how='left')

   movieId  rating                             title       genres
0      318     153  Shawshank Redemption, The (1994)  Crime|Drama

#### Задание 2
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [4]:
"""
Все считал в countries
Потом начал фильтровать по очереди и записывать результат в filtered_countries:
1) Отфильтровал по категории 4, 12 и 21
2) Отфильтровал по названию стран Latvia, Lithuania, Estonia
3) Отфильтровал по году с 2005 по 2010 года
4) Отфильтровал по quantity > 0
Далее оставил только стоблцы country, quantity, сгруппировал по стране и для каждой группы посчитал сумму quantity
"""

countries = pd.read_csv('power.csv')
filtered_countries = countries[(countries['category'] == 4) | (countries['category'] == 12) | (countries['category'] == 21)]
filtered_countries = filtered_countries[(filtered_countries['country'] == 'Latvia') | (filtered_countries['country'] == 'Lithuania') | (filtered_countries['country'] == 'Estonia')]
filtered_countries = filtered_countries[(filtered_countries['year'] >= 2005) & (filtered_countries['year'] <= 2010)]
filtered_countries = filtered_countries[filtered_countries['quantity'] > 0]
filtered_countries[['country', 'quantity']].groupby('country').sum('quantity')

           quantity
country
Estonia     63440.0
Latvia      54844.0
Lithuania  122296.0

#### Задание 3
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти): \
https://fortrader.org/quotes \
https://www.finanz.ru/valyuty/v-realnom-vremeni

In [5]:
"""
Как я понял, то нужно просто считать html-таблица в датафрейм.
Так и сделал
Для наглядности вывел каждую таблицу в цикле, отделяя каждую чертой.
"""

table_data = pd.read_html('https://fortrader.org/quotes',  encoding='utf-8')
for table in table_data:
    print(table)
    print('\n-------------------------------------------------------------------------------\n')

                           Название   Цена  Изменение  Изменение(%)  Обновлено
0  EURRUB Курс евро к рублю сегодня  89.14        0.0           0.0        NaN
1       USDRUB Курс рубля к доллару  73.56        0.0           0.0        NaN

-------------------------------------------------------------------------------

                              Название    Цена  Изменение  Изменение(%)  \
0       Нефть Brent Курс нефти сегодня   68.21       0.02          0.03
1          Нефть WTI Цены на нефть WTI   64.83       0.01          0.02
2  Природный газ Цена на природный газ    2.97      -0.01         -0.17
3                                 Кофе  153.35       0.00          0.00
4                             Кукуруза  731.00       0.00          0.00
5                                  Соя  441.80      -0.20         -0.05
6                               Хлопок   89.66       0.00          0.00

   Обновлено
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
6        NaN

-------------------------------------------------------------------------------

                           Название   Цена  Изменение  Изменение(%)  Обновлено
0       Золото Цена золота на бирже  1 831       -1.0         -0.00        NaN
1  Серебро Цена на серебро на бирже  27.45        0.0          0.00        NaN
2         Палладий Цена на Палладий  2 921       -2.0         -0.00        NaN
3           Платина Цены на платину  1 257        0.0          0.00        NaN
4           Медь Цена меди на бирже   4.75       -0.0         -0.04        NaN

-------------------------------------------------------------------------------

                                        Название      Цена  Изменение  \
0                                  ВТБ Акции ВТБ  0.052725    0.00000
1                         Газпром Акции газпрома    241.51   -0.19000
2                            Лукойл Акции Лукойл   6 087.5   -0.50000
3                        Роснефть Акции Роснефти    536.20    0.00000
4                       Сбербанк Акции Сбербанка    317.80   -0.14000
5           Сургутнефтегаз Акции Сургутнефтегаза    35.450   -0.02500
6                      Норникель Акции Норникель    27 000    0.00000
7                       Аэрофлот Акции Аерофлота     65.56   -0.08000
8                    Северсталь Акции Северсталь  1 834.60   -1.00000
9                    Транснефть Акции Транснефть   139 050 -100.00000
10             Ростелеком Курс акций ростелекома    104.71   -0.05000
11                      РУСАЛ Акции РУСАЛ (RUAL)    55.880   -0.02000
12      Детский мир iDreamSky Technology Limited    154.20   -0.02000
13             Петропавловск Акции Петропавловск     26.74    0.00000
14                    Алроса Акции АЛРОСА (ALRS)   113.840   -0.01000
15                    Магнит Акции Магнит (MGNT)   5 128.5   -1.00000
16                        НМЛК Акции НЛМК (NLMK)   276.080    0.06000
17                  М.видео Акции М.видео (MVID)    698.20   -0.20000
18    Газпром нефть Акции "Газпром нефть" (SIBN)    373.70   -0.20000
19                        НМТП Акции НМТП (NMTP)    7.4400   -0.01000
20            Полиметалл Акции Полиметалл (POLY)  1 660.80   -1.50000
21        Полюс Золото Акции Полюс Золото (PLZL)  15 070.5    0.00000
22                  НОВАТЭК Акции НОВАТЭК (NVTK)  1 418.20   -1.40000
23                РусГидро Акции РусГидро (HYDR)    0.8430   -0.00050
24                Татнефть Акции Татнефть (TATN)    512.60    0.10000
25        АФК Система Акции АФК "Система" (AFKS)    33.800    0.00000
26                                 МТС Акции МТС    324.00   -0.05000
27                Башнефть Акции Башнефть (BANE)   1 551.5   -2.00000
28                    Яндекс Акции Яндекс (YNDX)   4 827.4   -4.20000
29  X5 Retail Group Акции X5 Retail Group (FIVE)  2 375.00   -0.50000
30                  ФСК ЕЭС Акции ФСК ЕЭС (FEES)   0.21976   -0.00014
31                      Мечел Акции Мечел (MTLR)     78.50   -0.05000
32                МосБиржа Акции МосБиржа (MOEX)    187.36   -0.01000
33              Интер РАО Акции Интер РАО (IRAO)      5.09    0.00000
34              Mail.ru Акции Mail.ru (MAIL, ДР)  1 636.40   -0.40000
35                        Киви Акции Киви (QIWI)     789.5   -1.50000
36                  Лента Акции Лента (LNTA, ДР)    230.30   -0.40000
37            Тинькофф Акции Тинькофф (TCSG, др)  4 522.20   -1.60000
38                        Озон Акции Озон (Ozon)  4 440.50    0.00000

    Изменение(%)  Обновлено
0        0.00000        NaN
1       -0.08000        NaN
2       -0.00000        NaN
3        0.00000        NaN
4       -0.04000        NaN
5       -0.07000        NaN
6        0.00000        NaN
7       -0.12000        NaN
8       -0.05000        NaN
9       -0.00000        NaN
10      -0.05000        NaN
11      -0.03600        NaN
12      -0.01000        NaN
13       0.00000        NaN
14      -0.00900        NaN
15      -0.00000        NaN
16       0.02200        NaN
17      -0.03000        NaN
18      -0.05000        NaN
19      -0.13420        NaN
20      -0.09000        NaN
21       0.00000        NaN
22      -0.10000        NaN
23      -0.05930        NaN
24       0.02000        NaN
25       0.00000        NaN
26      -0.02000        NaN
27      -0.10000        NaN
28      -0.10000        NaN
29      -0.02000        NaN
30      -0.06367        NaN
31      -0.06000        NaN
32      -0.01000        NaN
33       0.00000        NaN
34      -0.02000        NaN
35      -0.20000        NaN
36      -0.17000        NaN
37      -0.04000        NaN
38       0.00000        NaN

-------------------------------------------------------------------------------

                               Название      Цена  Изменение  Изменение(%)  \
0           Google Акции Google (GOOGL)  2 351.03      -0.90         -0.04
1                   IBM Акции IBM (IBM)    145.40      -0.06         -0.04
2     Microsoft Акции Майкрософт (MSFT)    252.50       0.04          0.02
3              Apple Акции Apple (AAPL)    130.30       0.09          0.07
4                  Yandex Акции яндекса     64.80      -0.81         -1.23
5                   Toyota Акции Тойоты    150.11      -3.54         -2.30
6      Volkswagen Курс акций Volkswagen    210.05      -0.05         -0.02
7            Amazon Акции Amazon (AMZN)  3 289.74      -1.87         -0.06
8           Boeing Акции Boeing Company    235.50       0.03          0.01
9              Intel Акции Intel (INTC)     57.71       0.04          0.07
10            Coca-Cola Акции Coca-Cola     54.46      -0.05         -0.09
11         Netflix Акции Netflix (NFLX)    503.11      -0.73         -0.14
12            Pfizer Акции Pfizer (PFE)     39.51      -0.07         -0.18
13                        AMD Акции AMD     78.82       0.01          0.01
14  Walt Disney Акции Walt Disney (DIS)    184.85       0.01          0.01
15           NVIDIA Акции NVIDIA (NVDA)    592.49       0.00          0.00
16           PayPal Акции PayPal (PYPL)    253.10      -0.26         -0.10
17         Facebook Акции Facebook (FB)    319.00      -0.08         -0.03
18             Tesla Акции Тесла (TSLA)    671.51      -0.86         -0.13
19            Twiter Цена акций твитера     53.79       0.00          0.00
20    Hasbro Цена на акции Hasbro, Inc.     97.80      -1.35         -1.36
21                               Сименс    143.96       0.08          0.06
22                                 Qiwi     10.67      -0.03         -0.28
23     Mastercard Акции Mastercard (МА)    374.21      -1.19         -0.32
24         Moderna Акции Модерна (MRNA)    163.25       0.10          0.06
25        Макдональдс Акции Макдональдс    233.88      -0.96         -0.41
26                                 MSCI    460.00     -22.31         -4.63
27                             FIXPRICE      9.38      -0.02         -0.21
28                 Zoom Акции Zoom (ZM)    295.00      -0.24         -0.08
29     HeadHunter Акции HeadHunter (HH)     35.23      -6.83        -16.24

    Обновлено
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
5         NaN
6         NaN
7         NaN
8         NaN
9         NaN
10        NaN
11        NaN
12        NaN
13        NaN
14        NaN
15        NaN
16        NaN
17        NaN
18        NaN
19        NaN
20        NaN
21        NaN
22        NaN
23        NaN
24        NaN
25        NaN
26        NaN
27        NaN
28        NaN
29        NaN

-------------------------------------------------------------------------------

  Название      Цена  Изменение  Изменение(%)  Обновлено
0     FXIT  10 298.0     3.0000        0.0000        NaN
1     FXRU     952.6    -0.2000       -0.0000        NaN
2     FXDE   3 126.0    -2.0000       -0.1000        NaN
3     FXCN   3 903.0    -0.5000       -0.0000        NaN
4     FXGD    911.80    -0.2000       -0.0200        NaN
5     FXWO    1.8285    -0.0005       -0.0273        NaN

-------------------------------------------------------------------------------

                                         Название       Цена  Изменение  \
0         Индекс МосБиржи Индекс МосБиржи (IMOEX)    363 600    -250.00
1                    Индекс РТС Индекс РТС (RTSI)   1 577.51       0.00
2                      Dow Jones Индекс Dow Jones  34 777.80       0.00
3                          S&P 500 Индекс S&P 500      4 228       1.00
4                    Nasdaq 100 Индекс Nasdaq 100  13 719.60       0.00
5   Euro Stoxx 50 Индекс Euro Stoxx 50 (STOXX50E)    4 035.9       1.00
6                            FTSE 100 Индекс FTSE   7 129.71       0.00
7             Nikkei 225 Индекс Nikkei 225 (N225)     29 399       9.00
8                Russell 2000 Индекс Russell 2000   2 145.97       0.00
9                              DAX30 Индекс DAX30   15 362.0       0.00
10                           CAC 40 Индекс CAC 40    6 388.7       1.00
11                         IBEX 35 Индекс IBEX 35    9 072.3       0.00
12                         ASX 200 Индекс ASX 200    7 079.9       5.00
13        Фьючерс РТС Курс фьючерса на индекс РТС    154 910     -30.00
14                                      USD INDEX      90.21       0.01

    Изменение(%)  Обновлено
0          -0.00        NaN
1           0.00        NaN
2           0.00        NaN
3           0.00        NaN
4           0.00        NaN
5           0.00        NaN
6           0.00        NaN
7           0.00        NaN
8           0.00        NaN
9           0.00        NaN
10          0.00        NaN
11          0.00        NaN
12          0.10        NaN
13         -0.00        NaN
14          0.01        NaN

-------------------------------------------------------------------------------

                                           Название       Цена  Изменение  \
0                         EUR/USD Евро / Доллар США    1.21610   -0.00021
1                         GBP/USD Фунт / Доллар США    1.39859   -0.00014
2                            USD/CHF Доллар / Франк    0.90037   -0.00002
3                         USD/JPY Доллар США / Иена  108.59700    0.01900
4                             USD/CNH Доллар / Юань    6.41380    0.00000
5             USD/CAD Доллар США / Канадский доллар    1.21265    0.00013
6         AUD/USD Австралийский доллар / Доллар США    0.78428   -0.00010
7                              EUR/CHF Евро / Франк    1.09505   -0.00012
8   AUD/CAD Австралийский доллар / Канадский доллар    0.95102   -0.00010
9                      EUR/JPY Евро / Японская йена  132.06800   -0.01200
10                              EUR/GBP Евро / Фунт    0.86927   -0.00025
11                              GBP/JPY Фунт / Йена  151.87700    0.00600
12            NZDUSD New Zealand Dollar / US Dollar    0.72809    0.00043

    Изменение(%)  Обновлено
0       -0.01727        NaN
1       -0.01001        NaN
2       -0.00222        NaN
3        0.01700        NaN
4        0.00000        NaN
5        0.01072        NaN
6       -0.01275        NaN
7       -0.01096        NaN
8       -0.01051        NaN
9       -0.00900        NaN
10      -0.02875        NaN
11       0.00400        NaN
12       0.05909        NaN

-------------------------------------------------------------------------------

                                             Название       Цена  Изменение  \
0                               Bitcoin Курс биткоина  57 648.00   45.40000
1          Litecoin Курс лайткоин к доллару (LTC/USD)     348.82    4.06000
2   BitcoinCash Курс Биткоин кеш к доллару США (BC...   1 350.19   10.30000
3                                           Dash Dash     419.57   14.85000
4                                       Ripple Ripple     1.6006    0.02130
5                                   Ethereum Ethereum   3 502.88    5.12000
6                                         Zcash (ZEC)     333.66   13.95000
7                                           NEO (NEO)     120.81    2.86000
8                                           EOS (EOS)     10.211   -0.15400
9                                          TRON (TRX)    0.14941    0.00154
10                                             Monero     478.53   22.03000
11                                               IOTA     2.2526    0.07420
12                       ETC/USD эфириум классик, ETC     117.41   -2.64000

    Изменение(%)  Обновлено
0        0.08000        NaN
1        1.18000        NaN
2        0.77000        NaN
3        3.67000        NaN
4        1.34870        NaN
5        0.15000        NaN
6        4.36000        NaN
7        2.42000        NaN
8       -1.48600        NaN
9        1.04146        NaN
10       4.83000        NaN
11       3.40620        NaN
12      -2.20000        NaN

-------------------------------------------------------------------------------