### Домашнее задание «Функции и работа с данными»

#### Задание 1**
Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:\
* оценка 2 и меньше - низкий рейтинг
* оценка 4 и меньше - средний рейтинг
* оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class\
\**Домашнее задание к лекции.

In [62]:
import pandas as pd

In [63]:
"""
Сделал все как в условии, только приджойнил датафрейм с названием фильмов, чтобы было вывелось название фильма
Я подумал так наглядней. Ну и вывел 50 первых строк, чтобы попались фильмы всех рейтингов
"""

def classification_film(rating):
    if rating <= 2:
        return 'низкий рейтинг'
    elif rating <= 4:
        return 'средний рейтинг'
    else:
        return 'высокий рейтинг'

film_data = pd.read_csv('ml-latest-small/ratings.csv')
movies = pd.read_csv('ml-latest-small/movies.csv')
film_data['classification'] = film_data['rating'].apply(classification_film)
joined_data = film_data.merge(movies, on='movieId', how='left')
joined_data.head(50)

,userId,movieId,rating,timestamp,classification,title,genres
0,1,31,2.5,1260759144,средний рейтинг,Dangerous Minds (1995),Drama
1,1,1029,3.0,1260759179,средний рейтинг,Dumbo (1941),Animation|Children|Drama|Musical
2,1,1061,3.0,1260759182,средний рейтинг,Sleepers (1996),Thriller
3,1,1129,2.0,1260759185,низкий рейтинг,Escape from New York (1981),Action|Adventure|Sci-Fi|Thriller
4,1,1172,4.0,1260759205,средний рейтинг,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama
5,1,1263,2.0,1260759151,низкий рейтинг,"Deer Hunter, The (1978)",Drama|War
6,1,1287,2.0,1260759187,низкий рейтинг,Ben-Hur (1959),Action|Adventure|Drama
7,1,1293,2.0,1260759148,низкий рейтинг,Gandhi (1982),Drama
8,1,1339,3.5,1260759125,средний рейтинг,Dracula (Bram Stoker's Dracula) (1992),Fantasy|Horror|Romance|Thriller
9,1,1343,2.0,1260759131,низкий рейтинг,Cape Fear (1991),Thriller
10,1,1371,2.5,1260759135,средний рейтинг,Star Trek: The Motion Picture (1979),Adventure|Sci-Fi
11,1,1405,1.0,1260759203,низкий рейтинг,Beavis and Butt-Head Do America (1996),Adventure|Animation|Comedy|Crime
12,1,1953,4.0,1260759191,средний рейтинг,"French Connection, The (1971)",Action|Crime|Thriller
13,1,2105,4.0,1260759139,средний рейтинг,Tron (1982),Action|Adventure|Sci-Fi
14,1,2150,3.0,1260759194,средний рейтинг,"Gods Must Be Crazy, The (1980)",Adventure|Comedy
15,1,2193,2.0,1260759198,низкий рейтинг,Willow (1988),Action|Adventure|Fantasy
16,1,2294,2.0,1260759108,низкий рейтинг,Antz (1998),Adventure|Animation|Children|Comedy|Fantasy
17,1,2455,2.5,1260759113,средний рейтинг,"Fly, The (1986)",Drama|Horror|Sci-Fi|Thriller
18,1,2968,1.0,1260759200,низкий рейтинг,Time Bandits (1981),Adventure|Comedy|Fantasy|Sci-Fi
19,1,3671,3.0,1260759117,средний рейтинг,Blazing Saddles (1974),Comedy|Western
20,2,10,4.0,835355493,средний рейтинг,GoldenEye (1995),Action|Adventure|Thriller
21,2,17,5.0,835355681,высокий рейтинг,Sense and Sensibility (1995),Drama|Romance
22,2,39,5.0,835355604,высокий рейтинг,Clueless (1995),Comedy|Romance
23,2,47,4.0,835355552,средний рейтинг,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
24,2,50,4.0,835355586,средний рейтинг,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
25,2,52,3.0,835356031,средний рейтинг,Mighty Aphrodite (1995),Comedy|Drama|Romance
26,2,62,3.0,835355749,средний рейтинг,Mr. Holland's Opus (1995),Drama
27,2,110,4.0,835355532,средний рейтинг,Braveheart (1995),Action|Drama|War
28,2,144,3.0,835356016,средний рейтинг,"Brothers McMullen, The (1995)",Comedy
29,2,150,5.0,835355395,высокий рейтинг,Apollo 13 (1995),Adventure|Drama|IMAX
30,2,153,4.0,835355441,средний рейтинг,Batman Forever (1995),Action|Adventure|Comedy|Crime
31,2,161,3.0,835355493,средний рейтинг,Crimson Tide (1995),Drama|Thriller|War
32,2,165,3.0,835355441,средний рейтинг,Die Hard: With a Vengeance (1995),Action|Crime|Thriller
33,2,168,3.0,835355710,средний рейтинг,First Knight (1995),Action|Drama|Romance
34,2,185,3.0,835355511,средний рейтинг,"Net, The (1995)",Action|Crime|Thriller
35,2,186,3.0,835355664,средний рейтинг,Nine Months (1995),Comedy|Romance
36,2,208,3.0,835355511,средний рейтинг,Waterworld (1995),Action|Adventure|Sci-Fi
37,2,222,5.0,835355840,высокий рейтинг,Circle of Friends (1995),Drama|Romance
38,2,223,1.0,835355749,низкий рейтинг,Clerks (1994),Comedy
39,2,225,3.0,835355552,средний рейтинг,Disclosure (1994),Drama|Thriller
40,2,235,3.0,835355664,средний рейтинг,Ed Wood (1994),Comedy|Drama
41,2,248,3.0,835355896,средний рейтинг,Houseguest (1994),Comedy
42,2,253,4.0,835355511,средний рейтинг,Interview with the Vampire: The Vampire Chroni...,Drama|Horror
43,2,261,4.0,835355681,средний рейтинг,Little Women (1994),Drama
44,2,265,5.0,835355697,высокий рейтинг,Like Water for Chocolate (Como agua para choco...,Drama|Fantasy|Romance
45,2,266,5.0,835355586,высокий рейтинг,Legends of the Fall (1994),Drama|Romance|War|Western
46,2,272,3.0,835355767,средний рейтинг,"Madness of King George, The (1994)",Comedy|Drama
47,2,273,4.0,835355779,средний рейтинг,Mary Shelley's Frankenstein (Frankenstein) (1994),Drama|Horror|Sci-Fi
48,2,292,3.0,835355492,средний рейтинг,Outbreak (1995),Action|Drama|Sci-Fi|Thriller
49,2,296,4.0,835355395,средний рейтинг,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller

#### Задание 2
Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

In [59]:
"""
Сделал как в условии. 
Только подумал следующее: если использовать в лоб, то запросы, где регионы склоняются - не найдутся.
Например 'москве' при поиске в лоб не найдется и будет undefined.
Подумал что так неправильно. Решил модернизировать поиск.
Вы в одном вебинаре рассказывали про расстояние Левенштейна, решил, что можно попробовать ее использовать.
По идее расстояние Левенштейна должно быть либо 0, либо 1 
Потому что 'москве' от 'москва' отличается на один символ - тоже самое по другим регионам
Соответственно, если в запросе есть слов,
у которого расстояние Левенштейна с искомым городом ровно 0 или 1 - нужный запрос
Вот в циклах перебрал все и сделал простую проверку на это расстояние
Для наглядности вывел для региона 'петербург' - работает
"""


import Levenshtein as lvst

geo_data = {'Центр': ['москва', 'тула', 'ярославль'],
            'Северо-Запад': ['петербург', 'псков', 'мурманск'],
            'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
           }

def geo_classificator(keyword):
    list_keyword = keyword.split(' ')
    for region in geo_data:
        for city in geo_data[region]:
            for item in list_keyword:
                if lvst.distance(item, city) <= 1:
                    return city
    
    return 'undefined'

keywords = pd.read_csv('ml-latest-small/keywords.csv')
keywords['region'] = keywords['keyword'].apply(geo_classificator)
filtered_keywords = keywords[keywords['region'] == 'петербург']
filtered_keywords

                                                keyword   shows     region
370                            авито ру санкт петербург  425134  петербург
564                           погода в санкт петербурге  292489  петербург
1236                               банк санкт петербург  174375  петербург
1346                                    санкт петербург  144232  петербург
2550                 банк санкт петербург интернет банк   89123  петербург
...                                                 ...     ...        ...
97433               авито санкт петербурге недвижимость    3720  петербург
98726                    ледовый дворец санкт петербург    3772  петербург
99084  122 медсанчасть санкт петербург официальный сайт    3679  петербург
99134    росреестр по санкт петербургу официальный сайт    3700  петербург
99204                        bileter ru санкт петербург    3661  петербург

[193 rows x 3 columns]

#### Задание 3 (бонусное)

Есть мнение, что “раньше снимали настоящее кино, не то что сейчас”. Ваша задача проверить это утверждение, используя файлы с рейтингами фильмов из прошлого домашнего занятия (файл movies.csv и ratings.csv из базы https://grouplens.org/datasets/movielens). Т. е. проверить верно ли, что с ростом года выпуска фильма его средний рейтинг становится ниже.

При этом мы не будем затрагивать субьективные факторы выставления этих рейтингов, а пройдемся по следующему алгоритму:

    1. В переменную years запишите список из всех годов с 1950 по 2010.

    2. Напишите функцию production_year, которая каждой строке из названия фильма выставляет год выпуска. Не все названия фильмов содержат год выпуска в одинаковом формате, поэтому используйте следующий алгоритм:
        1. для каждой строки пройдите по всем годам списка years
        2. если номер года присутствует в названии фильма, то функция возвращает этот год как год выпуска
        3. если ни один из номеров года списка years не встретился в названии фильма, то возвращается 1900 год

    3. Запишите год выпуска фильма по алгоритму пункта 2 в новый столбец ‘year’

    4. Посчитайте средний рейтинг всех фильмов для каждого значения столбца ‘year’ и отсортируйте результат по убыванию рейтинга

In [38]:
"""
Сделал как в условии:
Сделал функцию production_year, передал в нее название фильма и статикой список годов
Сделал проверку и вернул год из списка, если тру, если ничего не нашлось - 1900
Применил функцию на столбце title и записал в новый столбец year этого датафрейма
Сгруппировал по year с подсчетом среднего значения рейтинга фильмов за этот год
Сбросил индекс, отсортировал по убыванию рейтинга и вывел 60 первых строк - потому что всего получилось 60 лет
(так вывелось все)
"""

def production_year(title, years = list(range(1950,2011))):
    for year in years:
        if str(year) in title:
            return int(year)
        else:
            pass
    
    return 1900
    
film_data = pd.read_csv('ml-latest-small/ratings.csv')
movies = pd.read_csv('ml-latest-small/movies.csv')
joined_data = film_data.merge(movies, on='movieId', how='left')
joined_data['year'] = joined_data['title'].apply(production_year)

joined_data.groupby('year').mean()['rating'].reset_index().sort_values('rating', ascending=False).head(60)

    year    rating
8   1957  4.014241
23  1972  4.011136
3   1952  4.000000
5   1954  3.994220
2   1951  3.983539
25  1974  3.978704
13  1962  3.952446
1   1950  3.915254
28  1977  3.905786
15  1964  3.841492
10  1959  3.841033
9   1958  3.823171
26  1975  3.823077
20  1969  3.817376
18  1967  3.814516
11  1960  3.809211
27  1976  3.806794
24  1973  3.806667
30  1979  3.777966
32  1981  3.758763
4   1953  3.754587
6   1955  3.751724
22  1971  3.748830
19  1968  3.737844
17  1966  3.736726
31  1980  3.708816
14  1963  3.705966
21  1970  3.700000
16  1965  3.678715
12  1961  3.663851
34  1983  3.657635
35  1984  3.651486
33  1982  3.638306
42  1991  3.628265
7   1956  3.617647
38  1987  3.606015
0   1900  3.602960
36  1985  3.588998
39  1988  3.552990
29  1978  3.549003
58  2007  3.548538
45  1994  3.537963
61  2010  3.537157
44  1993  3.536664
40  1989  3.534349
37  1986  3.528265
60  2009  3.520378
57  2006  3.511478
59  2008  3.498057
55  2004  3.491490
49  1998  3.472754
46  1995  3.472118
50  1999  3.471692
43  1992  3.466754
52  2001  3.460052
53  2002  3.456297
41  1990  3.449169
56  2005  3.448434
54  2003  3.444777
47  1996  3.426600